---
abstract: 'Add a SOURCE section (repository defaults to GitHub)'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-Weaver-Section-Source-DefaultGitHub
requires:
  Moose: 0
  Moose::Autobox: 0
  Pod::Weaver::Role::Section: 0
  perl: 5.010001
resources: {}
version: 0.03
